# Generated by Django 4.2.30 on 2026-06-19 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0008_alter_dataconnection_connection_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataconnection',
            name='connection_type',
            field=models.CharField(choices=[('postgresql', 'PostgreSQL'), ('mysql', 'MySQL'), ('databricks', 'Databricks'), ('db2', 'DB2'), ('oracle', 'Oracle'), ('csv', 'Flat File (CSV)'), ('parquet', 'Flat File (Parquet)'), ('excel', 'Flat File (Excel)'), ('text', 'Flat File (Text)')], max_length=20),
        ),
    ]
