"""
Migration: Create hwm_chk trigger tracking table.
This table is used by the DB Trigger scheduler to detect when a workflow
should be executed based on an ETL flag set by upstream processes.
"""
from django.db import migrations


def create_hwm_table(apps, schema_editor):
    vendor = schema_editor.connection.vendor
    with schema_editor.connection.cursor() as cursor:
        if vendor == 'sqlite':
            cursor.execute("""
                CREATE TABLE IF NOT EXISTS hwm_chk (
                    id           INTEGER PRIMARY KEY AUTOINCREMENT,
                    trigger_name VARCHAR(255) NOT NULL,
                    hwm_flag     CHAR(1)      NOT NULL DEFAULT 'N',
                    etl_date     DATE         NOT NULL,
                    created_at   TIMESTAMP    DEFAULT CURRENT_TIMESTAMP
                );
            """)
        elif vendor == 'postgresql':
            cursor.execute("""
                CREATE TABLE IF NOT EXISTS hwm_chk (
                    id           SERIAL PRIMARY KEY,
                    trigger_name VARCHAR(255) NOT NULL,
                    hwm_flag     CHAR(1)      NOT NULL DEFAULT 'N',
                    etl_date     DATE         NOT NULL,
                    created_at   TIMESTAMP    DEFAULT CURRENT_TIMESTAMP
                );
            """)
        elif vendor == 'mysql':
            cursor.execute("""
                CREATE TABLE IF NOT EXISTS hwm_chk (
                    id           INT AUTO_INCREMENT PRIMARY KEY,
                    trigger_name VARCHAR(255) NOT NULL,
                    hwm_flag     CHAR(1)      NOT NULL DEFAULT 'N',
                    etl_date     DATE         NOT NULL,
                    created_at   TIMESTAMP    DEFAULT CURRENT_TIMESTAMP
                );
            """)
        elif vendor == 'oracle':
            cursor.execute("""
                CREATE TABLE hwm_chk (
                    id           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    trigger_name VARCHAR2(255) NOT NULL,
                    hwm_flag     CHAR(1)      DEFAULT 'N' NOT NULL,
                    etl_date     DATE         NOT NULL,
                    created_at   TIMESTAMP    DEFAULT CURRENT_TIMESTAMP
                );
            """)
        else:
            cursor.execute("""
                CREATE TABLE IF NOT EXISTS hwm_chk (
                    id           INTEGER PRIMARY KEY,
                    trigger_name VARCHAR(255) NOT NULL,
                    hwm_flag     CHAR(1)      NOT NULL DEFAULT 'N',
                    etl_date     DATE         NOT NULL,
                    created_at   TIMESTAMP    DEFAULT CURRENT_TIMESTAMP
                );
            """)

        # Create indexes
        if vendor == 'oracle':
            cursor.execute("CREATE INDEX idx_hwm_trigger_name ON hwm_chk(trigger_name)")
            cursor.execute("CREATE INDEX idx_hwm_etl_date     ON hwm_chk(etl_date)")
            cursor.execute("CREATE INDEX idx_hwm_trigger_date ON hwm_chk(trigger_name, etl_date)")
        else:
            cursor.execute("CREATE INDEX IF NOT EXISTS idx_hwm_trigger_name ON hwm_chk(trigger_name)")
            cursor.execute("CREATE INDEX IF NOT EXISTS idx_hwm_etl_date     ON hwm_chk(etl_date)")
            cursor.execute("CREATE INDEX IF NOT EXISTS idx_hwm_trigger_date ON hwm_chk(trigger_name, etl_date)")


def drop_hwm_table(apps, schema_editor):
    vendor = schema_editor.connection.vendor
    with schema_editor.connection.cursor() as cursor:
        if vendor == 'oracle':
            cursor.execute("DROP INDEX idx_hwm_trigger_date")
            cursor.execute("DROP INDEX idx_hwm_etl_date")
            cursor.execute("DROP INDEX idx_hwm_trigger_name")
            cursor.execute("DROP TABLE hwm_chk")
        else:
            cursor.execute("DROP INDEX IF EXISTS idx_hwm_trigger_date")
            cursor.execute("DROP INDEX IF EXISTS idx_hwm_etl_date")
            cursor.execute("DROP INDEX IF EXISTS idx_hwm_trigger_name")
            cursor.execute("DROP TABLE IF EXISTS hwm_chk")


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0003_alter_workflow_description_and_more'),
    ]

    operations = [
        migrations.RunPython(create_hwm_table, reverse_code=drop_hwm_table),
    ]
