# Generated by Django 4.2.30 on 2026-06-16 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('validations', '0006_validationrun_workflow'),
        ('workflows', '0005_workflow_db_trigger_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='recipient_email',
            field=models.CharField(blank=True, help_text='Email address to receive validation reports', max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='EmailNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('email_body', models.TextField()),
                ('attachment_path', models.CharField(blank=True, max_length=500, null=True)),
                ('sent_status', models.CharField(default='pending', max_length=20)),
                ('sent_time', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_notifications', to='validations.validationrun')),
                ('workflow', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_notifications', to='workflows.workflow')),
            ],
            options={
                'verbose_name': 'Email Notification',
                'ordering': ['-created_at'],
            },
        ),
    ]
