# Generated by Django 4.2.30 on 2026-06-16 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0006_workflow_recipient_email_emailnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailnotification',
            name='retry_count',
            field=models.IntegerField(default=0),
        ),
    ]
