# Generated by Django 4.2.30 on 2026-06-09 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validations', '0004_validationrun_parameters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='validationrun',
            name='date_filter_end',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='validationrun',
            name='date_filter_start',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='validationrun',
            name='source_date_filter_end',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='validationrun',
            name='source_date_filter_start',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='validationrun',
            name='target_date_filter_end',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='validationrun',
            name='target_date_filter_start',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
