# Generated by Django 4.2.30 on 2026-06-16 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0005_workflow_db_trigger_fields'),
        ('validations', '0005_alter_validationrun_date_filter_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='validationrun',
            name='workflow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validation_runs', to='workflows.workflow'),
        ),
    ]
