# Generated by Django 4.2.30 on 2026-06-09 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mappings', '0011_alter_mapping_date_filter_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapping',
            name='source_date_range_operator_end',
            field=models.CharField(default='<=', max_length=5),
        ),
        migrations.AddField(
            model_name='mapping',
            name='source_date_range_operator_start',
            field=models.CharField(default='>=', max_length=5),
        ),
        migrations.AddField(
            model_name='mapping',
            name='target_date_range_operator_end',
            field=models.CharField(default='<=', max_length=5),
        ),
        migrations.AddField(
            model_name='mapping',
            name='target_date_range_operator_start',
            field=models.CharField(default='>=', max_length=5),
        ),
    ]
