# Generated by Django 4.2.30 on 2026-06-16 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mappings', '0012_mapping_source_date_range_operator_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapping',
            name='source_catalog',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='mapping',
            name='target_catalog',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
